RADAR-base/radar-helm-charts

charts/catalog-server/Chart.yaml
charts/catalog-server/README.md
charts/catalog-server/values.yaml

Update the security context to user 101 which is needed for containers to access the volumes.
**Benefits**
The kafka-init and catalog-server container start successfully
Not known
This is required because the [dockerfile uses user 101](https://github.com/RADAR-base/RADAR-Schemas/blob/d770a8d8ebde7320b17a1a33ea5da2d8910c8f6e/Dockerfile#L66)
And if it is not the same user in the security context, the volume will not be accessible and give the following error- 
```
kubectl logs catalog-server-5f5dc645dc-nl852 -c kafka-init
rsync: [sender] opendir "/schema/conf/lost+found" failed: Permission denied (13)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1330) [sender=3.2.3] …
```

[catalog-server] Fix security context

---

charts/radar-jdbc-connector/Chart.yaml
charts/radar-jdbc-connector/README.md
charts/radar-jdbc-connector/values.yaml

Bump RADAR-JDBC-connector to version 10.3.1. See release and change info here: https://github.com/RADAR-base/RADAR-JDBC-Connector/releases/tag/v10.3.1

Bump radar-jdbc-connector

---

charts/app-config/Chart.yaml
charts/app-config/README.md
charts/app-config/templates/deployment.yaml

Right now deploying a new version of app-config to the cluster will cause the new pod to fail because it can not acquire a lock. With this change before an update all of the existing app-config pods will be deleted before creating a new pod. 
It would be ideal to not use the Recreate deployment strategy but first changes must be done to app-config allow it to acquire the lock. 
[Recreate Deployment
](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#recreate-deployment)

Recreate app-config pods after an upgrade

---

charts/management-portal/Chart.yaml
charts/management-portal/README.md
charts/management-portal/templates/secrets-postgres-keystore.yaml
charts/management-portal/values.yaml

This will allow defining the SSL certificate even when the charts and helmfile are in different repos.

Certificate for MP now can be defined as a variblable instead of a file

---

charts/radar-rest-sources-backend/Chart.yaml
charts/radar-rest-sources-backend/README.md
charts/radar-rest-sources-backend/templates/configmap.yaml

Fixes MP auth URL: removes trailing slash to enhance compatibility with older versions of the backend.

[radar-rest-sources-backend] Fix MP auth URL

---

charts/radar-gateway/Chart.yaml
charts/radar-gateway/README.md
charts/radar-gateway/templates/configmap.yaml
charts/radar-gateway/values.yaml

In the radar-gateway ingress, match the max body size with the default max body size internally in radar-gateway. This avoids _413  Request Entity Too Large_ HTTP responses for data that could well be accepted by the gateway.
**Checklist**

[radar-gateway] Explicitly set max body size for Kafka uploads

---

charts/radar-output/Chart.yaml
charts/radar-output/README.md
charts/radar-output/templates/configmap-restructure.yaml
charts/radar-output/templates/deployment.yaml
charts/radar-output/values.yaml

Updates radar-output from version 2.0.1 to 2.2.0. This version has more efficient parallelism, fewer vulnerabilities, and fixes some OkHttp connection leaks. Includes configurability for javaOpts, individual topics, and source and target HTTP timeouts.

[radar-output] Update radar-output to 2.2.0

---

charts/kube-prometheus-stack/Chart.yaml
charts/kube-prometheus-stack/README.md
charts/kube-prometheus-stack/values.yaml

Fixes issue reported in https://github.com/RADAR-base/RADAR-Kubernetes/issues/201#issuecomment-1219243439.
**Checklist**

[kube-prometheus-stack] Fix Nginx ingress class error

---

charts/radar-jdbc-connector/Chart.yaml
charts/radar-jdbc-connector/README.md
charts/radar-jdbc-connector/templates/_helpers.tpl
charts/radar-jdbc-connector/templates/configmap.yaml
charts/radar-jdbc-connector/templates/deployment.yaml
charts/radar-jdbc-connector/values.yaml

- adds support for both JDBC source and sink connectors
- make JDBC configuration in line with other helm charts
This change is not completely backwards compatible with older radar-jdbc-connector charts, so any deployments that use it should update their configuration.
**Checklist**

[radar-jdbc-connector] Update radar jdbc connector version and config

---

charts/radar-rest-sources-authorizer/Chart.yaml
charts/radar-rest-sources-authorizer/README.md
charts/radar-rest-sources-authorizer/values.yaml
charts/radar-rest-sources-backend/Chart.yaml
charts/radar-rest-sources-backend/README.md
charts/radar-rest-sources-backend/values.yaml

Updates rest sources authorizer and rest sources backend chart version to 4.0.1.  This inculdes Garmin OAuth1 fixes.
**Checklist**

[rest-sources-authorizer] Update version to 4.0.1

---

charts/radar-jdbc-connector/Chart.yaml
charts/radar-jdbc-connector/README.md
charts/radar-jdbc-connector/templates/_helpers.tpl
charts/radar-jdbc-connector/templates/configmap.yaml
charts/radar-jdbc-connector/templates/deployment.yaml
charts/radar-jdbc-connector/templates/pvc.yaml
charts/radar-jdbc-connector/values.yaml

Adds some properties to the source connector to make it functional. Notable differences:
- autocreate topics for the tables
- add record key by selecting a single field
- use Avro formatting
- add error logs
- only scan a single database schema by default

[radar-jdbc-connector] Add source connector properties

---

charts/radar-rest-sources-authorizer/Chart.yaml
charts/radar-rest-sources-authorizer/README.md
charts/radar-rest-sources-authorizer/templates/deployment.yaml

Fix the health check of the radar-rest-sources-authorizer.
**Checklist**

[radar-rest-sources-authorizer] Fix healthcheck

---

charts/catalog-server/Chart.yaml
charts/catalog-server/README.md
charts/catalog-server/templates/configmap.yaml

Transforms keys of `kafkaProperties` values, replacing `_` with `.`. This restores documented behaviour and actual of chart version <0.4.0. @yatharthranjan could you test if this indeed fixes #60?
**Checklist**

[catalog-server] Transform catalog-server as documented

---

external/trivy/.helmignore
external/trivy/Chart.yaml
external/trivy/README.md
external/trivy/templates/NOTES.txt
external/trivy/templates/_helpers.tpl
external/trivy/templates/configmap.yaml
external/trivy/templates/ingress.yaml
external/trivy/templates/podsecuritypolicy.yaml
external/trivy/templates/role.yaml
external/trivy/templates/rolebinding.yaml
external/trivy/templates/secret.yaml
external/trivy/templates/service.yaml
external/trivy/templates/serviceaccount.yaml
external/trivy/templates/statefulset.yaml
external/trivy/values.yaml

Trivy continuously scans Kubernetes cluster for security issues, and generates security reports by watching Kubernetes for state changes and automatically triggering scans in response to changes, for example initiating a vulnerability scan when a new Pod is created.
Example output:
```
kubectl get vulnerabilityreports -o wide
NAME                                                            REPOSITORY                                TAG                    SCANNER   AGE   CRITICAL   HIGH   MEDIUM   LOW   UNKNOWN
replicaset-57fffd77d6                                           radarbase/radar-rest-source-authorizer    4.0.0                  Trivy     20h   4          16     13       2     0
replicaset-6577cf85bc                                           ingress-nginx/controller …
```

Added trivy scanner

---

charts/catalog-server/Chart.yaml
charts/catalog-server/README.md
charts/catalog-server/values.yaml
charts/radar-rest-sources-authorizer/Chart.yaml
charts/radar-rest-sources-authorizer/README.md
charts/radar-rest-sources-authorizer/values.yaml
charts/radar-rest-sources-backend/Chart.yaml
charts/radar-rest-sources-backend/README.md
charts/radar-rest-sources-backend/values.yaml
charts/radar-s3-connector/Chart.yaml
charts/radar-s3-connector/README.md
charts/radar-s3-connector/templates/configmap.yaml
charts/radar-s3-connector/templates/deployment.yaml
charts/radar-s3-connector/values.yaml

- Adds a S3 region if necessary
- Enable object tagging
- Fix catalog server
- Use a base image for getting topics that already has `jq` and `curl`
- Bump rest source authoriser.
**Checklist**

[radar-s3-connector/catalog-server] Fix s3 connector with region and topic generation

---

charts/radar-rest-sources-backend/Chart.yaml
charts/radar-rest-sources-backend/README.md
charts/radar-rest-sources-backend/templates/_helpers.tpl
charts/radar-rest-sources-backend/templates/configmap.yaml

Fixes setting with empty rest source clients (null instead of empty list).
**Checklist**

[radar-rest-sources-backend] Fix empty rest source clients error

---

charts/radar-rest-sources-authorizer/Chart.yaml
charts/radar-rest-sources-authorizer/README.md
charts/radar-rest-sources-authorizer/values.yaml
charts/radar-rest-sources-backend/Chart.yaml
charts/radar-rest-sources-backend/README.md
charts/radar-rest-sources-backend/templates/configmap.yaml
charts/radar-rest-sources-backend/values.yaml

Updated image versions for radar-rest-sources-* and made redis variable optional for backwards compatibility.
**Checklist**

[radar-rest-sources-*] Updated image versions and made redis optional

---

charts/radar-s3-connector/Chart.yaml
charts/radar-s3-connector/README.md
charts/radar-s3-connector/templates/configmap.yaml
charts/radar-s3-connector/values.yaml

- Bumps radar-s3-connector from 7.3.0 to 7.3.1
- Fixes object tagging value; it would be overridden by a fixed value in configmaps.
**Checklist**

[radar-s3-connector] bump tag and fix object tagging

---

charts/radar-home/Chart.yaml
charts/radar-home/README.md
charts/radar-home/templates/deployment.yaml
charts/radar-home/values.yaml

[radar-home 0.1.3](https://github.com/RADAR-base/radar-home/releases/tag/v0.1.3) adds appconfig link.
**Checklist**

[radar-home] Added appconfig link

---

charts/management-portal/Chart.yaml
charts/management-portal/README.md
charts/management-portal/values.yaml

For some reason using `1.7Gi` was failing and had to use `1700Mi` instead.

Change MP resource request format

---

charts/radar-appserver/Chart.yaml
charts/radar-appserver/README.md
charts/radar-appserver/values.yaml

- Update to appserver version 2.0.1
- Breaking change in this version: Removes XMPP notifications support
**Checklist**

[radar-appserver] Update to version 2.0.1

---

charts/radar-appserver/Chart.yaml
charts/radar-appserver/README.md
charts/radar-appserver/values.yaml

Appserver release info: 
https://github.com/RADAR-base/RADAR-Appserver/releases/tag/v2.3.0

Update to appserver 2.3.0 to be compatible with MP 2.0

---

charts/management-portal/Chart.yaml
charts/management-portal/README.md
charts/management-portal/templates/ingress-rate-limited.yaml
charts/management-portal/values.yaml

I've discovered that rate limiting hasn't been working properly in RADAR-Kubernetets, this PR should solve the issue with introducing a separate ingress resource only for rate limited paths.

Fixed MP rate limiting

---

charts/radar-appserver/Chart.yaml
charts/radar-appserver/README.md
charts/radar-appserver/values.yaml

- Update appserver to release 2.4.1
**Benefits**
- Fixes deadlock in fetching protocols and fixes UserMetrics and User cyclic dependency
- fixes #
**Checklist**

[radar-appserver] Update to version 2.4.1

---

charts/management-portal/Chart.yaml
charts/management-portal/README.md
charts/management-portal/templates/deployment.yaml
charts/management-portal/values.yaml

Add values for ory idp to management-portal chart 1.1.2 --> 1.1.3
**Benefits**
Support using a separate idp instead of integrated into management-portal
NA
Performed in keyvans absence
**Checklist**

management-portal 1.1.2 --> 1.1.3 add ory idp

---

charts/radar-integration/Chart.yaml
charts/radar-integration/README.md
charts/radar-integration/templates/configmap.yaml
charts/radar-integration/values.yaml

- Add support for attributes in radar-integration configmap
**Benefits**
- fixes #
**Checklist**

[radar-integration] Update configmap

---

charts/s3-proxy/Chart.yaml
charts/s3-proxy/README.md
charts/s3-proxy/values.yaml

Update the s3-proxy chart to use the latest released image (2.2.0)
**Benefits**
more up to date images used
none that I can think of
NA
**Checklist**

s3-proxy chart to appversion 2.2.0

---

charts/radar-s3-connector/Chart.yaml
charts/radar-s3-connector/README.md
charts/radar-s3-connector/values.yaml

Update the radar-s3-connector pod to the latest appversion
**Benefits**
Security updates
This image still uses java 11 and should be update again later
NA
**Checklist**

radar-s3-connector 0.3.2

---

charts/velero-s3-deployment/Chart.yaml
charts/velero-s3-deployment/README.md
external/velero/values.yaml

Fixes BackfOffLimit Exceeded due to libc.so.6: version `GLIBC_2.33' not found, as mentioned upstream at https://github.com/vmware-tanzu/helm-charts/issues/550
**Benefits**
One will be able to deploy RADAR with Velero because it is currently not possible. This was an unnoticed regression.
Uses a specific version of Debian but, because this is in an init container, it does not involve security issues in the long term.
- fixes https://github.com/RADAR-base/RADAR-Kubernetes/pull/242#issuecomment-1997186331
**Checklist**

 velero: bugfix: BackOffLimitExceeded GLIBC not found

---

charts/radar-push-endpoint/Chart.yaml
charts/radar-push-endpoint/README.md
charts/radar-push-endpoint/templates/servicemonitor.yaml

Fixes the build issue in [Radar-Kubernetes ](https://github.com/RADAR-base/RADAR-Kubernetes/actions/runs/8643715295/job/24414441396#step:8:1279)
```
Release "radar-push-endpoint" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(ServiceMonitor.spec.selector): unknown field "app.kubernetes.io/instance" in com.coreos.monitoring.v1.ServiceMonitor.spec.selector, ValidationError(ServiceMonitor.spec.selector): unknown field "app.kubernetes.io/managed-by" in com.coreos.monitoring.v1.ServiceMonitor.spec.selector, ValidationError(ServiceMonitor.spec.selector): unknown field "app.kubernetes.io/name" in com.coreos.monitoring.v1.ServiceMonitor.spec.selector, …
```

Fixed radar-push-endpoint servicemonitor

---

README.md
charts/data-dashboard-backend/.helmignore
charts/data-dashboard-backend/Chart.yaml
charts/data-dashboard-backend/README.md
charts/data-dashboard-backend/README.md.gotmpl
charts/data-dashboard-backend/templates/NOTES.txt
charts/data-dashboard-backend/templates/_helpers.tpl
charts/data-dashboard-backend/templates/configmap.yaml
charts/data-dashboard-backend/templates/deployment.yaml
charts/data-dashboard-backend/templates/hpa.yaml
charts/data-dashboard-backend/templates/ingress.yaml
charts/data-dashboard-backend/templates/secrets.yaml
charts/data-dashboard-backend/templates/service.yaml
charts/data-dashboard-backend/templates/tests/test-connection.yaml
charts/data-dashboard-backend/values.yaml
charts/radar-output/templates/deployment.yaml

We are in the process of implementing a new backend service named _data dashboard backend_ that acts as a common source for data present in the _timescale db_ storage.
This PR will:
- add the helm chart for this service named _data dashboard backend_
- update the README.md with instructions to run _helm-docs_ with docker

[data-dashboard-backend] Add helmchart for data dashboard backend service

---

charts/management-portal/Chart.yaml
charts/management-portal/README.md
charts/management-portal/values.yaml
charts/radar-appserver/Chart.yaml
charts/radar-appserver/README.md
charts/radar-appserver/values.yaml
charts/radar-rest-sources-backend/Chart.yaml
charts/radar-rest-sources-backend/README.md
charts/radar-rest-sources-backend/values.yaml
charts/radar-upload-connect-backend/Chart.yaml
charts/radar-upload-connect-backend/README.md
charts/radar-upload-connect-backend/values.yaml

- An error occurs when the network policy pod selector host name is > 63 characters, this will truncate that value
- Truncate postgres podselector so that it is within 63 character limit (update MP, appserver, upload-backend, and rest-sources-backend network policy egress)
**Benefits**
- fixes #
**Checklist**

Update egress network policy of some charts

---

charts/radar-gateway/Chart.yaml
charts/radar-gateway/README.md
charts/radar-gateway/values.yaml

Update the radar-gateway chart to appversion 0.7.1
**Benefits**
Security updates
None
NA
**Checklist**

radar-gateway chart to appversion 0.7.1

---

charts/catalog-server/Chart.yaml
charts/catalog-server/README.md
charts/catalog-server/values.yaml

Update the catalog server chart to appversion 0.8.8
**Benefits**
Security updates for the catalog server
None
NA
The hotfix was applied due to an issue with accessing the confluent-cloud platform
**Checklist**

catalog-server to appversion 0.8.8

---

README.md
charts/data-dashboard-backend/Chart.yaml
charts/data-dashboard-backend/README.md
charts/data-dashboard-backend/templates/configmap.yaml
charts/data-dashboard-backend/templates/deployment.yaml
charts/data-dashboard-backend/values.yaml
charts/management-portal/Chart.yaml
charts/management-portal/README.md
charts/management-portal/values.yaml

Data dashboard backend is a new service that exposes data from the _observations_ table in _timescaledb_ database (provisioned by KSQLDB service) to frontend/mobile applications. This PR will improve the helm chart for this service.
**Checklist**

[data-dashboard-backend] Add charts for data dashboard backend service

---

charts/radar-gateway/Chart.yaml
charts/radar-gateway/README.md
charts/radar-gateway/values.yaml

Nginx decodes the uri before passing it to the backend server. This is dangerous because it can allow for XSS attacks. Grizzly servers have a bug where they send the decoded uri as part of error messages (see https://github.com/Graylog2/graylog2-server/issues/3171).
To prevent XSS attacks, we need to re-encode the uri ($request_uri is the original encoded request) before passing it to the Grizzly server.

[radar-gateway] Configure radar-gataway to mitigate XSS attack vector

---

charts/cert-manager-letsencrypt/Chart.yaml
charts/cert-manager-letsencrypt/README.md
charts/cert-manager-letsencrypt/templates/clusterissuer.yaml
charts/cert-manager-letsencrypt/values.yaml

Allow to configure ingress class for HTTP-01 solver for certmanager (letsencrypt)
**Benefits**
Allows to use different than default ingress in cases where there are multiple in the cluster and you need to handle certificates for the non-default one.
Also handles the case, where you're using the ingressClassNamre matching on your ingress instead of the legacy annotation way. The default is set for the legacy approach.
N/A
N/A
N/A
**Checklist**

[cert-manager-letsencrypt] Allow to override ingress class for HTTP solver

---

charts/radar-integration/Chart.yaml
charts/radar-integration/README.md
charts/radar-integration/values.yaml

MP url was incorrect in the redcap integration helm chart (did not contain the trailing /). This updates the mp url.
**Benefits**
- fixes #
**Checklist**

[radar-integration] Fix MP url

---

charts/data-dashboard-backend/Chart.yaml
charts/data-dashboard-backend/README.md
charts/data-dashboard-backend/templates/configmap.yaml
charts/data-dashboard-backend/values.yaml
charts/management-portal/Chart.yaml
charts/management-portal/README.md
charts/management-portal/values.yaml

Main changes:
- TLS secret name was renamed to match nomenclature of other secrets
- Added JDBC properties for the service needed to comply with JDBC-connector generated database table
- Fixed default MP scopes needed for data-dashboard-backend to work

[data-dashboard-backend] Several fixes to chart

---

charts/catalog-server/Chart.yaml
charts/catalog-server/README.md
charts/catalog-server/templates/deployment.yaml
charts/catalog-server/values.yaml

The helm chart of _catalog-server_ does not correctly reference two env vars defined in RADAR-Schemas. The `KAFKA_NUM_REPLICATION` and `KAFKA_NUM_PARTITIONS` of RADAR-Schemas are referenced as `RADAR_NUM_REPLICATION_FACTOR` and `RADAR_NUM_PARTITIONS`, respectively. From the RADAR-Schemas Dockefile:
```
ENV KAFKA_SCHEMA_REGISTRY=http://schema-registry-1:8081 \
...
KAFKA_NUM_PARTITIONS=3 \
KAFKA_NUM_REPLICATION=3 \
KAFKA_NUM_BROKERS=3 \
...
```
This breaks the mechanism where the _kafka_num_brokers_ can set the number of brokers because the KAFKA_NUM_REPLICATION is not controller accordingly.
This PR will:
- fix the env var names. 
- externalize the values for `KAFKA_NUM_REPLICATION` and `KAFKA_NUM_PARTITIONS` to the values.yaml file.

Fix names of KAFKA_NUM_PARTITIONS and KAFKA_NUM_REPLICATION of RADAR-Schemas

---

charts/radar-s3-connector/Chart.yaml
charts/radar-s3-connector/README.md
charts/radar-s3-connector/values.yaml

See subject. Documentation was missing on this property.

Fix description of kafka_num_brokers value

---

.gitattributes

Add a gitattribute to ensure automatic normalization of line endings for new files.
**Benefits**
Prevent files being checked in with the wrong line-endings, so that everyone can count on consistent line-endings in the whole repo.
-
-
This was done in an effort to improve the contributor experience on windows, as troubles with lin-endings there cause failing CI jobs. It is a part of [this step by step guide to changing the line-endings in the repo locally](https://stackoverflow.com/a/13154031).
**Checklist**

Add gitattribute to help with correct helm-docs formatting

---

charts/data-dashboard-backend/Chart.yaml
charts/data-dashboard-backend/README.md
charts/data-dashboard-backend/templates/ingress.yaml
charts/data-dashboard-backend/values.yaml

Ingress was broken because of missing Ingress class name

[data-dashboard-backend] Add classname to Ingress

---

charts/radar-gateway/Chart.yaml
charts/radar-gateway/README.md
charts/radar-gateway/values.yaml

It seems like memory value should be percentage value instead of bytes.

[radar-gateway] Fixed default HPA memory

---

charts/catalog-server/Chart.yaml
charts/catalog-server/README.md
charts/catalog-server/templates/deployment.yaml
charts/catalog-server/values.yaml

[catalog-server] Upgrade to appversion 0.8.10

---

charts/management-portal/Chart.yaml
charts/management-portal/README.md
charts/management-portal/templates/deployment.yaml
charts/management-portal/values.yaml

Add support for the configuration of AAL2 and the identityserver login url to managementportal.
**Benefits**
we can set these values
The development of MP is currently very active, and these variables may change relatively soon
-
**Checklist**

[management-portal] Support setting AAL2 and identityserver login url

---

charts/radar-appserver/Chart.yaml
charts/radar-appserver/README.md
charts/radar-appserver/templates/deployment.yaml
charts/radar-appserver/templates/secrets.yaml
charts/radar-appserver/values.yaml

This PR will pass SMTP connection credentials to the Appserver application. When value `smtp.enabled=true`, Appserver will send notifications via email alongside push notifications.
**Note**
This feature depends on a new version of Appserver that is not yet available. The version bump will happen when new app version exists.
**Checklist**

[radar-appserver] Add SMTP server configuration to send notifications via email

---

external/graylog/Chart.lock
external/graylog/Chart.yaml

To fix the build on main branch I think we first need to remove the ES from graylog and then added it again. This PR removes it and when the build works will make another PR to return it.

Removed ES from graylog

---

charts/radar-appserver/Chart.yaml
charts/radar-appserver/README.md

In #240 the appserver image have changed to 2.4.3 instead of 2.4.2. This PR will downgrade the appversion to the correct version.

Downgrade radar appserver

---

charts/radar-rest-sources-authorizer/Chart.yaml
charts/radar-rest-sources-authorizer/README.md
charts/radar-rest-sources-authorizer/templates/deployment.yaml
charts/radar-rest-sources-authorizer/values.yaml
charts/radar-rest-sources-backend/Chart.yaml
charts/radar-rest-sources-backend/README.md
charts/radar-rest-sources-backend/templates/configmap.yaml
charts/radar-rest-sources-backend/templates/deployment.yaml
charts/radar-rest-sources-backend/values.yaml

Update the rest source authorizer images
**Benefits**
Bugfix
-
NA
**Checklist**

[rest-source-auth] Update rest-source-authorizer to 4.4.3

---

charts/radar-gateway/Chart.yaml
charts/radar-gateway/README.md
charts/radar-gateway/values.yaml

Radar gateway uses around 400MB of memory on idle mode, the requests now reflect that. HPA based on memory isn't very useful at the moment and it has been disabled.

[radar-gateway] Tune memory configuration

---

charts/radar-rest-sources-authorizer/Chart.yaml
charts/radar-rest-sources-authorizer/README.md
charts/radar-rest-sources-authorizer/templates/deployment.yaml
charts/radar-rest-sources-backend/Chart.yaml
charts/radar-rest-sources-backend/README.md
charts/radar-rest-sources-backend/templates/configmap.yaml

These slashes caused errors in the rest source authorizer frontend.

Remove trailing slashes in rest-sources-backend URLs

---

charts/s3-proxy/Chart.yaml
charts/s3-proxy/README.md
charts/s3-proxy/templates/deployment.yaml
charts/s3-proxy/values.yaml

Fix s3-connector 2.3.0 app version

---

charts/radar-appserver/Chart.yaml
charts/radar-appserver/README.md
charts/radar-appserver/templates/deployment.yaml
charts/radar-appserver/templates/secrets.yaml
charts/radar-appserver/values.yaml

This PR adds helm chart configuration for the new file upload endpoint of appserver.

Add upload config to appserver chart

---

charts/velero-s3-deployment/Chart.yaml
charts/velero-s3-deployment/README.md
charts/velero-s3-deployment/templates/deployment.yaml
charts/velero-s3-deployment/values.yaml

The app version was incorrectly derived from the Velero app version.

[bugfix] Fix minio mc app version for velero chart

---

charts/catalog-server/Chart.yaml
charts/catalog-server/README.md

[version] Up catalog-server to app version 0.8.11

---

charts/radar-rest-sources-authorizer/Chart.yaml
charts/radar-rest-sources-authorizer/README.md
charts/radar-rest-sources-authorizer/templates/deployment.yaml
charts/radar-rest-sources-authorizer/values.yaml

CONNECT uses the intermediate implementation of Ory for 2FA. Bastiaan implemented this on a different MP URL. We previously removed the value _authUrl_ that allowed to set this custom URL. 
This PR reinstes the _authUrl_ parameter.
It can be removed when the final implementation of Ory Kratos/Hydra has been released.

Reinstate authUrl value for rest-sources-authorizer

---

charts/radar-appserver/Chart.yaml
charts/radar-appserver/README.md
charts/radar-appserver/templates/ingress.yaml
charts/radar-appserver/values.yaml

Config option _nginx.ingress.kubernetes.io/proxy-body-size_ was missing from the ingess to enable upload of large files.

Set ingress proxy-body-size when upload enabled in appserver

---

charts/data-dashboard-backend/Chart.yaml
charts/data-dashboard-backend/README.md
charts/data-dashboard-backend/templates/networkpolicy.yaml
charts/data-dashboard-backend/values.yaml
charts/radar-self-enrolment-ui/Chart.yaml
charts/radar-self-enrolment-ui/README.md
charts/radar-self-enrolment-ui/templates/networkpolicy.yaml
charts/radar-self-enrolment-ui/values.yaml

Two charts that has been added recently but they didn't have network policy. It's added now.

Added network policy to 2 charts

---

charts/radar-gateway/Chart.yaml
charts/radar-gateway/README.md
charts/radar-gateway/templates/deployment.yaml
charts/radar-gateway/templates/jmx-configmap.yaml
charts/radar-gateway/templates/service.yaml
charts/radar-push-endpoint/Chart.yaml
charts/radar-push-endpoint/README.md
charts/radar-push-endpoint/templates/deployment.yaml
charts/radar-push-endpoint/templates/jmx-configmap.yaml
charts/radar-push-endpoint/templates/service.yaml

Although the charts allow for disabling service monitoring, monitoring-related resources were created for radar-gateway and radar-push-endpoint. This would claim unneccessary resources on local test and development deploymen.
This PR removes Kubernetes assets from radar-gateway and radar-push-endpoint when monitoring is disabled.

Do not include jmx pods when monitoring is disabled

---

charts/radar-fitbit-connector/Chart.yaml
charts/radar-fitbit-connector/README.md
charts/radar-fitbit-connector/templates/configmap-properties.yaml
charts/radar-fitbit-connector/values.yaml

During e2e testing of the Fitbit connector we cannot mock the Fitbit API since the URL is hardcoded.
This PR will update the chart to make the Fitbit URL configurable.

Allow configuration of Fitbit API url

---

charts/radar-gateway/Chart.yaml
charts/radar-gateway/README.md
charts/radar-gateway/templates/configmap.yaml
charts/radar-gateway/values.yaml

Previous PR introduced public key endpoint for radar-gateway. This implementation did not include config for a sensible default value.
This PR will provide a default value that respects the protocol (http, https) which is needed for local testing.

Create default public key endpoint for radar-gateway

---

charts/radar-upload-connect-backend/Chart.yaml
charts/radar-upload-connect-backend/README.md
charts/radar-upload-connect-backend/values.yaml

Since we reuse PostgreSQL chart and change its name, the selector label also needs to change to match that.
```
labels:
app.kubernetes.io/component: primary
app.kubernetes.io/instance: radar-upload-postgresql
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/name: postgresql
apps.kubernetes.io/pod-index: "0"
controller-revision-hash: radar-upload-postgresql-7c65bcc55c
helm.sh/chart: postgresql-12.1.9
statefulset.kubernetes.io/pod-name: radar-upload-postgresql-0
```

Fixed radar upload backend network policy

---

charts/radar-gateway/Chart.yaml
charts/radar-gateway/README.md
charts/radar-gateway/values.yaml

[radar-gateway] Allow config of request timeouts 

---

charts/radar-fitbit-connector/Chart.yaml
charts/radar-fitbit-connector/README.md
charts/radar-fitbit-connector/templates/configmap-properties.yaml
charts/radar-fitbit-connector/templates/deployment.yaml
charts/radar-fitbit-connector/values.yaml

At present the interval between refresh actions of the registered FitBit users is hard-coded and of very long (1hr). This makes using the FitBit connector in an e2e-test difficult.
This PR will allow external configuration the 1) main application loop and 2) expiry of the FitBit user cache. This way e2e-tests can use shorter refresh intervals.

[radar-fitbit-connector] Allow config of application intervals

---

charts/radar-output/Chart.yaml
charts/radar-output/README.md
charts/radar-output/templates/configmap.yaml
charts/radar-output/values.yaml

[radar-output] Allow config of scan intervals (needed for e2e testing)

---

charts/data-dashboard-backend/Chart.yaml
charts/data-dashboard-backend/README.md
charts/data-dashboard-backend/templates/configmap.yaml
charts/data-dashboard-backend/values.yaml

[data-dashboard-backend] Change path for api to /dashboard-data

---

charts/radar-gateway/Chart.yaml
charts/radar-gateway/README.md
charts/radar-gateway/templates/_helpers.tpl
charts/radar-gateway/templates/deployment.yaml
charts/radar-gateway/values.yaml

JMX exporter image didn't had the ability to configure image registry, this PR adds that feature.

[radar-gateway] Add image registry config to exporter image

---

.github/bin/external_docker_image_matrix
.github/workflows/scheduled-snyk-docker.yaml

Detected vulnerabilities were reported to the Security tab before. The management of many reports was not very convenient in the Security section. I decided to switch to Issues because these 1) are automatically removed after branch upgrade, and 2) can be removed manually.

Report vulnerabilities to Issues on GitHub 

---

charts/radar-gateway/Chart.yaml
charts/radar-gateway/README.md
charts/radar-gateway/templates/_helpers.tpl
charts/radar-gateway/templates/deployment.yaml
charts/radar-gateway/values.yaml

Implements [RB-153](https://thehyve.atlassian.net/browse/RB-153)
Open Telemetry allows for distributed tracing of events in the RADARbase deployment. Sentry has support for Open Telemetry by including a sentry-opentelemetry-agent in each service in the deployment. 
This PR includes OpenTelemetry configuration with Sentry agent to radar-gateway.
Depends on https://github.com/RADAR-base/radar-commons/pull/181

[radar-gateway] Update radar-gateway helm chart for Opentelemetry config.

---

charts/radar-gateway/Chart.yaml
charts/radar-gateway/README.md

This update of radar gateway adds the open telemetry jar which was previously missing

fix: up radar gateway to version 0.9.1

---

charts/radar-hydra/Chart.yaml
charts/radar-hydra/README.md
external/hydra/Chart.lock
external/hydra/Chart.yaml
external/hydra/README.md
external/hydra/charts/hydra-maester/Chart.yaml
external/hydra/charts/hydra-maester/README.md
external/hydra/templates/_helpers.tpl
external/hydra/templates/ingress-admin.yaml
external/hydra/templates/ingress-public.yaml

In the previous commit I omitted the hydra-maester subchart for  the external hydra chart. This PR:
1. Updates the external-hydra chart to v0.53.0
2. Adds the missing hydra-maester sub-chart.

fix: add missing hydra-maester external chart

---

charts/radar-cloudnative-postgresql/Chart.yaml
charts/radar-cloudnative-postgresql/README.md
charts/radar-cloudnative-postgresql/templates/_helpers.tpl
charts/radar-cloudnative-postgresql/templates/secret-users.yaml
charts/radar-cloudnative-postgresql/values.yaml
charts/radar-self-enrolment-ui/Chart.yaml
charts/radar-self-enrolment-ui/README.md
charts/radar-self-enrolment-ui/templates/_helpers.tpl
charts/radar-self-enrolment-ui/templates/secret.yaml

In the chart updates for _self-enrolment-portal_ and _cloudnative-postgresql_ random generation of secrets was implemented incorrectly (error between redeploys). This PR corrects this problem by:
1. Removal of the incorrect use of the `common.secrets.password.manage` function.
2. Implement correct password generation logic for persistence of pre-extisting secrets.

Fix: persist-secrets-between-updates

---

.github/workflows/lint-test.yaml
charts/radar-fitbit-connector/Chart.yaml
charts/radar-fitbit-connector/README.md
charts/radar-fitbit-connector/templates/configmap-properties.yaml
charts/radar-fitbit-connector/values.yaml
charts/radar-oura-connector/Chart.yaml
charts/radar-oura-connector/README.md
charts/radar-oura-connector/templates/configmap-properties.yaml
charts/radar-oura-connector/values.yaml

- Allow configurable `auth_url` in both `radar-fitbit-connector` and `radar-oura-connector` for deployments that use Hydra auth (default is still MP auth url)
- Currently manually updated in deployments, but would be good to have this configurable in the chart itself
**Benefits**
- Allows Hydra auth
- fixes #
- Depends on https://github.com/RADAR-base/RADAR-REST-Connector/pull/163
**Checklist**

[radar-rest-connectors] Allow configurable auth_url

---

.github/workflows/scheduled-snyk-docker.yaml

radar-backend service was deprecated and will be removed from the repository in the future. We should disable the weekly scan because there are 1.5k vulnerabilities reported for this service, interfering with effective detection of vulnerabilities in other components.

chore: remove radar-backend from weekly snyk scanning

---

charts/radar-nifi/Chart.yaml
charts/radar-nifi/README.md
charts/radar-nifi/charts/zookeeper/README.md
charts/radar-nifi/charts/zookeeper/values.yaml
charts/radar-postgresql/Chart.yaml
charts/radar-postgresql/README.md
charts/radar-postgresql/values.yaml

Bitnami has moved supported docker images to a paid license.
Legacy docker images (as used by RADAR-base) are still available in the bitnamilegacy repo. This PR will update _repository_ values for internal charts to the new repo.
Repo for external charts will be handled in PR to the RADAR-Kubernetes repo.

fix: use bitnamilegacy image repository

---

charts/radar-rest-sources-backend/Chart.yaml
charts/radar-rest-sources-backend/README.md
charts/radar-rest-sources-backend/values.yaml

This PR fixes the image name of the docker image for radar-rest-sources-backend.

[radar-rest-sources-backend] fix: rest sources authorizer backend docker image name
