RADAR-base/radar-helm-charts

Makefile
Adds the Makefile to the repository that will make generating docs easier
**Benefits**
- fixes #
**Checklist**
=> Added Makefile for generating docs

charts/radar-fitbit-connector/README.md, charts/radar-rest-sources-authorizer/README.md, charts/radar-rest-sources-backend/README.md, charts/radar-upload-connect-backend/Chart.yaml, charts/radar-upload-connect-backend/README.md, charts/radar-upload-connect-backend/templates/deployment.yaml, charts/radar-upload-source-connector/Chart.yaml, charts/radar-upload-source-connector/README.md, charts/radar-upload-source-connector/templates/configmap.yaml, charts/radar-upload-source-connector/templates/deployment.yaml
- Fixes health check of backend
- Improves health check of connector to fail when no more connectors are running
- Fixes casting of long integers in deployment (prevents numbers like 2e6 instead of 2000000).
**Checklist**
=> [radar-upload-source-*] Fix health check and variable casting

charts/app-config/Chart.yaml, charts/app-config/README.md, charts/app-config/values.yaml, charts/catalog-server/Chart.yaml, charts/catalog-server/README.md, charts/catalog-server/values.yaml, charts/radar-gateway/Chart.yaml, charts/radar-gateway/README.md, charts/radar-gateway/values.yaml, charts/radar-output/Chart.yaml, charts/radar-output/README.md, charts/radar-output/values.yaml, charts/radar-rest-sources-authorizer/Chart.yaml, charts/radar-rest-sources-authorizer/README.md, charts/radar-rest-sources-authorizer/values.yaml
Fixing log4shell issue
**Checklist**
=> Updated applications to fix log4shell

charts/radar-rest-sources-backend/Chart.yaml, charts/radar-rest-sources-backend/README.md, charts/radar-rest-sources-backend/values.yaml
_radar-rest-sources-backend_: Add `serverName` variable to `values.yaml`
**Checklist**
=> [radar-rest-sources-backend] Add serverName to values

charts/radar-jdbc-connector/Chart.yaml, charts/radar-jdbc-connector/README.md, charts/radar-jdbc-connector/templates/deployment.yaml, charts/radar-jdbc-connector/values.yaml
Adds SSL protocol configurations to the `radar-jdbc-connector` chart
**Benefits**
This will allow `SSL` communication as opposed to the default `PLAINTEXT`
- partially fixes #16
**Checklist**
=> Update radar-jdbc-connector chart

charts/management-portal/Chart.yaml, charts/management-portal/README.md, charts/management-portal/values.yaml
Bump MP to version 0.8.1.
Set replicas to 1, since by default it does not scale.
**Checklist**
=> [management-portal] Bump MP to version 0.8.1

charts/management-portal/Chart.yaml, charts/management-portal/README.md, charts/management-portal/templates/ingress.yaml
Add TLS secret name to ingress
=> [management-portal] Add TLS secret name to ingress

charts/radar-rest-sources-authorizer/Chart.yaml, charts/radar-rest-sources-authorizer/README.md, charts/radar-rest-sources-authorizer/values.yaml, charts/radar-rest-sources-backend/Chart.yaml, charts/radar-rest-sources-backend/README.md, charts/radar-rest-sources-backend/templates/configmap.yaml, charts/radar-rest-sources-backend/values.yaml
Updates radar-rest-sources-authorizer to version 4.0.0 including any configuration changes.
=> [radar-rest-sources-auth] Update radar-rest-sources-authorizer to version 4.0.0

charts/radar-jdbc-connector/Chart.yaml, charts/radar-jdbc-connector/README.md, charts/radar-jdbc-connector/values.yaml
- Bump JDBC connector docker image with updates from original repository and TimescaleDB dialect fixes
**Benefits**
- Fixes table field schema `NullPointerException` in the TimescaleDB dialect
- fixes https://github.com/RADAR-base/RADAR-Kubernetes/issues/192
**Checklist**
=> [radar-jdbc-connector] Bump jdbc connector image

charts/radar-appserver/Chart.yaml, charts/radar-appserver/README.md, charts/radar-appserver/templates/configmap.yaml, charts/radar-appserver/templates/deployment.yaml, charts/radar-appserver/templates/ingress.yaml, charts/radar-appserver/templates/secrets.yaml, charts/radar-appserver/values.yaml
Fixes ingress definition of radar-app server
**Checklist**
=> [radar-appserver] Fix ingress definition

charts/radar-gateway/Chart.yaml, charts/radar-gateway/README.md, charts/radar-gateway/templates/deployment.yaml, charts/radar-gateway/templates/hpa.yaml, charts/radar-gateway/values.yaml
update radar-gateway version and tweak its annotations and probe times.
**Checklist**
=> [radar-gateway] update version and tweak annotations and probe times

charts/radar-push-endpoint/Chart.yaml, charts/radar-push-endpoint/README.md, charts/radar-push-endpoint/templates/hpa.yaml
=> [push-endpoint] update HPA to remove deprecation warning for K8s 1.23+

external/common/Chart.yaml, external/common/README.md, external/common/templates/_affinities.tpl, external/common/templates/_capabilities.tpl, external/common/templates/_images.tpl, external/common/templates/_names.tpl, external/common/templates/_utils.tpl, external/common/templates/validations/_mongodb.tpl, external/common/templates/validations/_mysql.tpl, external/common/templates/validations/_redis.tpl
**Benefits**
- fixes #
**Checklist**
=> [bitnami/common] Updated to version 2.0.0

charts/radar-integration/Chart.yaml, charts/radar-integration/README.md, charts/radar-integration/templates/configmap.yaml
Removes some unneeded config values from the configmap (removed in recent versions of the application).
**Benefits**
- fixes #
**Checklist**
=> [radar-integration] Remove unneeded config

charts/radar-gateway/Chart.yaml, charts/radar-gateway/README.md, charts/radar-gateway/values.yaml
- Updates radar-gateway to 0.2.6 according to release 0.5.14 https://github.com/RADAR-base/RADAR-Gateway/releases/tag/v0.5.14
**Checklist**
=> [radar-gateway] Update version to 0.2.6

external/cert-manager/Chart.yaml, external/cert-manager/README.md, external/cert-manager/templates/_helpers.tpl, external/cert-manager/templates/cainjector-deployment.yaml, external/cert-manager/templates/cainjector-psp-clusterrolebinding.yaml, external/cert-manager/templates/cainjector-rbac.yaml, external/cert-manager/templates/cainjector-serviceaccount.yaml, external/cert-manager/templates/crds.yaml, external/cert-manager/templates/deployment.yaml, external/cert-manager/templates/networkpolicy-egress.yaml, external/cert-manager/templates/networkpolicy-webhooks.yaml, external/cert-manager/templates/psp-clusterrolebinding.yaml, external/cert-manager/templates/rbac.yaml, external/cert-manager/templates/service.yaml, external/cert-manager/templates/serviceaccount.yaml, external/cert-manager/templates/servicemonitor.yaml, external/cert-manager/templates/startupapicheck-job.yaml, external/cert-manager/templates/startupapicheck-psp-clusterrolebinding.yaml, external/cert-manager/templates/startupapicheck-rbac.yaml, external/cert-manager/templates/startupapicheck-serviceaccount.yaml, external/cert-manager/templates/webhook-config.yaml, external/cert-manager/templates/webhook-deployment.yaml, external/cert-manager/templates/webhook-mutating-webhook.yaml, external/cert-manager/templates/webhook-psp-clusterrolebinding.yaml, external/cert-manager/templates/webhook-rbac.yaml, external/cert-manager/templates/webhook-service.yaml, external/cert-manager/templates/webhook-serviceaccount.yaml, external/cert-manager/templates/webhook-validating-webhook.yaml, external/cert-manager/values.yaml
Update cert-manager from 1.8 to 1.10.
**Checklist**
=> [cert-manager] update to 1.10.1

charts/app-config-frontend/Chart.yaml, charts/app-config-frontend/README.md, charts/app-config-frontend/values.yaml, charts/app-config/Chart.yaml, charts/app-config/README.md, charts/app-config/values.yaml
=> [app-config] Bump version

charts/radar-rest-sources-authorizer/Chart.yaml, charts/radar-rest-sources-authorizer/README.md, charts/radar-rest-sources-authorizer/values.yaml, charts/radar-rest-sources-backend/Chart.yaml, charts/radar-rest-sources-backend/README.md, charts/radar-rest-sources-backend/values.yaml
=> [radar-rest-sources-auth] Update rest-source-authorizer

charts/radar-home/.helmignore, charts/radar-home/Chart.yaml, charts/radar-home/README.md, charts/radar-home/README.md.gotmpl, charts/radar-home/templates/_helpers.tpl, charts/radar-home/templates/deployment.yaml, charts/radar-home/templates/ingress.yaml, charts/radar-home/templates/service.yaml, charts/radar-home/templates/tests/test-connection.yaml, charts/radar-home/values.yaml
Adds radar-home chart.
**Checklist**
=> [radar-home] Added radar-home helm chart

charts/radar-jdbc-connector/Chart.yaml, charts/radar-jdbc-connector/README.md, charts/radar-jdbc-connector/templates/configmap.yaml, charts/radar-jdbc-connector/templates/deployment.yaml
**Benefits**
Made default JDBC variables overridable.  The variable like `CONNECT_REST_ADVERTISED_HOST_NAME` were not overridable because the variables are fetched in the beginning of the env component in [deployment.yaml](https://github.com/RADAR-base/radar-helm-charts/blob/de0d6cb2356c1bfea27c2bfeb36624ff000a6afa/charts/radar-jdbc-connector/templates/deployment.yaml#L52). This PR solved this issue. 
N/A
- fixes #75 
**Checklist**
=> [radar-jdbc-connector] jdbc default variable override

charts/app-config-frontend/Chart.yaml, charts/app-config-frontend/README.md, charts/app-config-frontend/values.yaml, charts/app-config/Chart.yaml, charts/app-config/README.md, charts/app-config/values.yaml, charts/management-portal/Chart.yaml, charts/management-portal/README.md, charts/management-portal/values.yaml, charts/radar-gateway/Chart.yaml, charts/radar-gateway/README.md, charts/radar-gateway/values.yaml, charts/radar-rest-sources-authorizer/Chart.yaml, charts/radar-rest-sources-authorizer/README.md, charts/radar-rest-sources-authorizer/values.yaml, charts/radar-rest-sources-backend/Chart.yaml, charts/radar-rest-sources-backend/README.md, charts/radar-rest-sources-backend/values.yaml
Update ManagementPortal to 2.0.0 and all dependent services
- https://github.com/RADAR-base/ManagementPortal/releases/tag/v2.0.0
- https://github.com/RADAR-base/radar-app-config/releases/tag/v0.5.0
- https://github.com/RADAR-base/radar-rest-source-auth/releases/tag/v4.3.0
- https://github.com/RADAR-base/radar-gateway/releases/tag/v0.6.0
=> Update all MP versions to 2.0.0

charts/radar-s3-connector/Chart.yaml, charts/radar-s3-connector/README.md, charts/radar-s3-connector/templates/configmap.yaml, charts/radar-s3-connector/values.yaml
Ensures that the radar-s3-connector initialisation fails completely if no topics are found.
=> Fix radar-s3-connector init and update images

charts/radar-fitbit-connector/Chart.yaml, charts/radar-fitbit-connector/README.md, charts/radar-fitbit-connector/templates/configmap-properties.yaml, charts/radar-fitbit-connector/templates/deployment.yaml, charts/radar-fitbit-connector/values.yaml
- update radar-fitbit-connector
- add kafka-wait properties to optionally avoid waiting for Kafka brokers or to supply additional connection properties.
=> [radar-fitbit-connector] update radar-fitbit-connector and add kafka-wait properties

charts/radar-gateway/Chart.yaml, charts/radar-gateway/README.md, charts/radar-gateway/values.yaml
Fixes deployment of RADAR-Questionnaire https://github.com/RADAR-base/RADAR-Questionnaire/pull/1706
=> [radar-gateway] Add Content-Encoding header for CORS

charts/radar-appserver/Chart.yaml, charts/radar-appserver/README.md, charts/radar-appserver/values.yaml
- Updates appserver version to use latest release `2.4.0` (https://github.com/RADAR-base/RADAR-Appserver/releases/tag/v2.4.0)
**Benefits**
- Cache questionnaires and standardize Github client access
- Use async processing to avoid database timeouts 
- Remove unused spring-data-rest dependency 
- fixes #100 
**Checklist**
=> [radar-appserver] Update to version 2.4.0

charts/radar-oura-connector/.helmignore, charts/radar-oura-connector/Chart.yaml, charts/radar-oura-connector/README.md, charts/radar-oura-connector/README.md.gotmpl, charts/radar-oura-connector/templates/_helpers.tpl, charts/radar-oura-connector/templates/configmap-properties.yaml, charts/radar-oura-connector/templates/deployment.yaml, charts/radar-oura-connector/templates/networkpolicy.yaml, charts/radar-oura-connector/templates/pvc.yaml, charts/radar-oura-connector/templates/service.yaml, charts/radar-oura-connector/templates/tests/test-connection.yaml, charts/radar-oura-connector/values.yaml
- Adds a new chart to support the deployment of the `radar-oura-connector`
- This REST connector pulls data from the Oura API and produces data to the Kafka topics
**Benefits**
- Allows us to pull data from Oura when the user is authorised in the `rest-sources-authorizer`
- fixes #
**Checklist**
=> [radar-oura-connector] Add new radar-oura-connector chart

charts/radar-oura-connector/Chart.yaml, charts/radar-oura-connector/README.md, charts/radar-oura-connector/templates/deployment.yaml
- Update `oura-connector` kafka-wait property which is causing string parsing issues
**Benefits**
- fixes #
**Checklist**
=> [radar-oura-connector] Update oura-connector kafka-wait property

charts/catalog-server/Chart.yaml, charts/catalog-server/README.md, charts/catalog-server/values.yaml
- Update to latest version of `radar-schemas-tools` `0.8.6`
**Benefits**
- fixes #
**Checklist**
=> [catalog-server] Update radar-schemas-tools image

.github/workflows/helm-publish.yml, external/redis/Chart.yaml
Hoping to fix the error in 
https://github.com/RADAR-base/radar-helm-charts/actions/runs/8908948989
=> upgrade chart-releaser-action

charts/radar-push-endpoint/Chart.yaml, charts/radar-push-endpoint/README.md, charts/radar-push-endpoint/values.yaml
Fixes an issue with the user repository token URL in radar-push-endpoint. Removes the trailing `/` which causes issues.
**Benefits**
- Issue reported on slack channels.
**Checklist**
=> [radar-push-endpoint] Fix user repository token URL 

charts/radar-gateway/Chart.yaml, charts/radar-gateway/README.md, charts/radar-gateway/templates/hpa.yaml, charts/radar-gateway/values.yaml
This was hardcoded before but now it can be changed via the configuration
=> [radar-gateway] Made HorizontalPodAutoscaler configurable

charts/data-dashboard-backend/Chart.yaml, charts/data-dashboard-backend/README.md
=> Set app version to v0.1.4 and up chart version

charts/data-dashboard-backend/Chart.yaml, charts/data-dashboard-backend/README.md
=> [data-dashboard-backend] Upgrade to appversion 0.1.7

charts/radar-jdbc-connector/Chart.yaml, charts/radar-jdbc-connector/README.md, charts/radar-jdbc-connector/templates/deployment.yaml, charts/radar-jdbc-connector/values.yaml
=> [radar-jdbc-connector] Upgrade to appversion 10.5.3

charts/radar-gateway/Chart.yaml, charts/radar-gateway/README.md, charts/radar-gateway/templates/deployment.yaml, charts/radar-gateway/values.yaml
=> [radar-gateway] Upgrade to appversion 0.7.2

charts/radar-fitbit-connector/Chart.yaml, charts/radar-fitbit-connector/README.md, charts/radar-fitbit-connector/templates/deployment.yaml, charts/radar-fitbit-connector/values.yaml
=> [radar-fitbit-connector] Upgrade to appversion 0.5.2

README.md, external/graylog/Chart.lock, external/graylog/Chart.yaml
=> Readded ES to graylog

charts/radar-jdbc-connector/Chart.yaml, charts/radar-jdbc-connector/README.md
=> [radar-jdbc-connector] Upgrade to appversion 10.5.3-hotfix

charts/catalog-server/Chart.yaml, charts/catalog-server/README.md, charts/catalog-server/templates/deployment.yaml
The appversion was not correctly passed after not defining _tag_ in values.yaml.
=> [catalog-server] Fix appversion in docker image tag

charts/radar-push-endpoint/Chart.yaml, charts/radar-push-endpoint/README.md, charts/radar-push-endpoint/templates/ingress.yaml, charts/radar-push-endpoint/values.yaml
Trying to fix the following warning:
```
W0731 15:18:47.853758  395615 warnings.go:70] path /push-endpoint/?(.*) cannot be used with pathType Prefix
```
=> Fix push endpoint ingress

charts/radar-fitbit-connector/Chart.yaml, charts/radar-fitbit-connector/README.md
see title
This will fix the error observed while running 0.5.2.
=> [radar-fitbit-connector] Update app version to 0.5.3

charts/management-portal/Chart.yaml, charts/management-portal/README.md
See title. Fixes two performance related issues.
=> [management-portal] Update app version to 2.1.4

external/graylog/Chart.yaml
Looks like I had to also bump the chart version for changes to take effect.
=> Bumped Graylog version

Makefile, external/ory-commons/.helmignore, external/ory-commons/Chart.yaml, external/ory-commons/templates/_helpers.tpl
Adds Ory commons required for building Ory component charts
**Benefits**
- fixes #
**Checklist**
=> [ory-commons] add ory-commons

charts/management-portal/Chart.yaml, charts/management-portal/README.md, charts/management-portal/templates/deployment.yaml, charts/management-portal/values.yaml
- Add support for auth server configs to allow use with external auth server like Ory Hydra
**Benefits**
- fixes #
**Checklist**
=> [management-portal] add support for auth server configs

charts/data-dashboard-backend/Chart.yaml, charts/data-dashboard-backend/README.md
=> Up data-dashboard-backend to app version 0.2.0

charts/data-dashboard-backend/Chart.yaml, charts/data-dashboard-backend/README.md
=> Up data-dashboard-backend to app version 0.2.1

charts/data-dashboard-backend/Chart.yaml, charts/data-dashboard-backend/README.md
=> Up data-dashboard-backend to app version 0.2.2

charts/app-config-frontend/Chart.yaml, charts/app-config-frontend/README.md, charts/app-config-frontend/values.yaml
=> [bugfix] Fix app-config-frontend app version

charts/radar-jdbc-connector/Chart.yaml, charts/radar-jdbc-connector/README.md
=> [security] Up jdbc-connector to app version 0.5.5

charts/app-config-frontend/Chart.yaml, charts/app-config-frontend/README.md, charts/app-config/Chart.yaml, charts/app-config/README.md, charts/radar-fitbit-connector/Chart.yaml, charts/radar-fitbit-connector/README.md, charts/radar-home/Chart.yaml, charts/radar-home/README.md, charts/radar-oura-connector/Chart.yaml, charts/radar-oura-connector/README.md, charts/radar-rest-sources-authorizer/Chart.yaml, charts/radar-rest-sources-authorizer/README.md, charts/radar-upload-connect-backend/Chart.yaml, charts/radar-upload-connect-backend/README.md, charts/radar-upload-connect-frontend/Chart.yaml, charts/radar-upload-connect-frontend/README.md, charts/radar-upload-source-connector/Chart.yaml, charts/radar-upload-source-connector/README.md
=> [security] Various-chart-updates

charts/radar-rest-sources-backend/Chart.yaml, charts/radar-rest-sources-backend/README.md
=> [security] Up rest-sources-backend to app version 4.4.4

charts/radar-home/Chart.yaml, charts/radar-home/README.md, charts/radar-home/values.yaml
Remove image tag hard coded in values.yaml.
=> Fix image tag for radar-home chart

charts/radar-rest-sources-authorizer/Chart.yaml, charts/radar-rest-sources-authorizer/README.md, charts/radar-rest-sources-backend/Chart.yaml, charts/radar-rest-sources-backend/README.md
=> Up rest-sources-auth app version to 4.4.6

charts/radar-rest-sources-authorizer/Chart.yaml, charts/radar-rest-sources-authorizer/README.md, charts/radar-rest-sources-backend/Chart.yaml, charts/radar-rest-sources-backend/README.md
=> Up rest-sources-auth app version to 4.4.7

charts/radar-gateway/Chart.yaml, charts/radar-gateway/README.md
=> [radar-gateway] Upgrade to app version 0.7.5

charts/radar-gateway/Chart.yaml, charts/radar-gateway/README.md
=> [radar-gateway] Upgrade app version to 0.7.6

charts/radar-fitbit-connector/Chart.yaml, charts/radar-fitbit-connector/README.md, charts/radar-oura-connector/Chart.yaml, charts/radar-oura-connector/README.md
This will enable configuration of app refresh timings during e2e-tests.
=> [radar-rest-source-connector] Update app versions to 0.6.0

external/common/Chart.yaml, external/common/README.md, external/common/templates/_affinities.tpl, external/common/templates/_compatibility.tpl, external/common/templates/_images.tpl, external/common/templates/_secrets.tpl, external/common/templates/_tplvalues.tpl, external/common/templates/_warnings.tpl, external/common/templates/validations/_cassandra.tpl, external/common/templates/validations/_mongodb.tpl, external/common/templates/validations/_mysql.tpl, external/common/templates/validations/_postgresql.tpl, external/common/templates/validations/_redis.tpl
This PR updates the common chart in the external directory. Some of the functionality in the newer version is needed for the upcoming PR.
=> Update bitnami common chart

charts/data-dashboard-backend/Chart.yaml, charts/data-dashboard-backend/README.md, charts/data-dashboard-backend/templates/deployment.yaml
Change default healthcheck path for data-dashboard-backend api 
165961633281808040a359f40c7ed3cf46ae09ad
=> [data-dashboard-backend] Fixed healthcheck

charts/radar-gateway/Chart.yaml, charts/radar-gateway/README.md, charts/radar-gateway/templates/deployment.yaml, charts/radar-gateway/values.yaml
Implement configuration for Sentry log monitoring for radar-gateway service.
=> Update radar-gateway helm chart for Sentry config

charts/radar-home/Chart.yaml, charts/radar-home/README.md, charts/radar-home/templates/deployment.yaml
This was piece of code was forgotten during the last update and it's been added now.
=> Fixed radar-home image config

.github/bin/external_docker_image_matrix, .github/workflows/scheduled-snyk-docker.yaml, .gitleaks.toml, .snyk, devbox.lock
This PR will add weekly snyk docker image scans for external images.
=> Add weekly snyk docker image scans for external images

.github/bin/external_docker_image_matrix, .github/workflows/scheduled-snyk-docker.yaml, .pre-commit-config.yaml, .snyk, charts/radar-gateway/Chart.yaml, charts/radar-gateway/README.md, charts/radar-gateway/values.yaml, charts/radar-push-endpoint/Chart.yaml, charts/radar-push-endpoint/README.md, charts/radar-push-endpoint/templates/_helpers.tpl, charts/radar-push-endpoint/templates/deployment.yaml, charts/radar-push-endpoint/values.yaml, external/grafana/Chart.yaml
- ignore elasticsearch vulnerabilities
- unify versions of docker images
- allow ignoring of certain docker images by pattern in action yaml file
=> Update docker image scans

.github/bin/external_docker_image_matrix, .github/workflows/scheduled-snyk-docker.yaml, .snyk, charts/radar-postgresql/Chart.yaml, charts/radar-postgresql/README.md, charts/radar-postgresql/values.yaml
=> Update docker image scans to ignore external depenency vulns

.github/workflows/docker_images_external.json, .github/workflows/scheduled-snyk-docker.yaml, .snyk
Were reported to the Security tab before. The management of many reports was not very convenient in the section. I decided to switch to Issues because these 1) are automatically removed after branch upgrade, and 2) can be removed manually.
=> feat: report vulnerabilities to Issues on GitHub

charts/management-portal/Chart.yaml, charts/management-portal/README.md, charts/radar-appserver/Chart.yaml, charts/radar-appserver/README.md, charts/radar-fitbit-connector/Chart.yaml, charts/radar-fitbit-connector/README.md, charts/radar-jdbc-connector/Chart.yaml, charts/radar-jdbc-connector/README.md, charts/radar-oura-connector/Chart.yaml, charts/radar-oura-connector/README.md, charts/radar-s3-connector/Chart.yaml, charts/radar-s3-connector/README.md, charts/radar-upload-source-connector/Chart.yaml, charts/radar-upload-source-connector/README.md, external/postgresql/values.yaml, external/redis/values.yaml
This PR patches detected vulnerabilities found during the March 2025 security review and update.
=> March 2025 security updates

charts/radar-self-enrolment-ui/Chart.yaml, charts/radar-self-enrolment-ui/README.md, charts/radar-self-enrolment-ui/templates/deployment.yaml, charts/radar-self-enrolment-ui/values.yaml
- Update env vars in SEP UI
- Updated timescaledb postgres db default value (required by pre-commit hook checks)
**Benefits**
- Allows SEP UI vars to be easier to configure instead of adding to `extraEnv`
- fixes #
**Checklist**
=> Update env vars in SEP UI

charts/radar-integration/Chart.yaml, charts/radar-integration/README.md, charts/radar-integration/templates/configmap.yaml
- Only add attributes to `radar.yml` when it is specified for the project, otherwise do not include the key
- Otherwise, there are parsing errors
**Benefits**
- fixes #
Depends on https://github.com/RADAR-base/RADAR-RedcapIntegration/pull/78
**Checklist**
=> [radar-integration] Fix attributes in configmap

.github/workflows/lint-test.yaml, charts/radar-rest-sources-backend/Chart.yaml, charts/radar-rest-sources-backend/README.md, charts/radar-rest-sources-backend/templates/_helpers.tpl, charts/radar-rest-sources-backend/templates/configmap.yaml, charts/radar-rest-sources-backend/templates/deployment.yaml
- Update `secret` config to allow using external DB such as RDS
- Add check if `jwksUrls` is present before adding to configmap, fixes spacing issue
- Remove default Management Portal public key env
**Benefits**
- fixes #
**Checklist**
=> [radar-rest-sources-backend] Update configmap and secrets

charts/radar-kafka/Chart.yaml, charts/radar-kafka/README.md, charts/radar-kafka/templates/nodepool.yaml, charts/radar-kafka/templates/prometheus-rules.yaml, charts/radar-kafka/values.yaml
**Benefits**
- fixes #
**Checklist**
=> feat: enable set resources requests for Kafka pods

charts/radar-kratos/Chart.yaml, charts/radar-kratos/README.md, charts/radar-kratos/values.yaml
This PR fixes a missing allowed return url for kratos.
=> fix: kratos allowed return url
